pittcsc/Summer2023-Internships

README.md

The internship was posted 10 months ago, so safe to say it was for Summer 2020.

remove 2020 jpl posting

---

README.md

**Companies Added:**
* PwC
* KPMG
* Deloitte
* CIA
* FBI
* Aflac
* State Farm
* Equifax
* Bank of America
* AT&T
* Verizon

Added various companies

---

README.md

- Software-Engineering-Summer-Internships

add NASA JPL

---

README.md

- Adds Google internships to README

Add Google internships

---

README.md

Looks like Snap has a separate application for Canadians that opened today; I added it here!

Adding link to Toronto application for Snap

---

README.md

Added link to LinkedIn job posting for Samsara.

Samsara 2021 SWE Internship

---

README.md

- One position open to all
- One exclusive to bachelor students

Remove ambiguity in mastercard positions

---

README.md

I also added my github handle on the README when I added the positions. Hope that's okay!

added playstation intern positions

---

README.md

Added Tanium

---

README.md

Squarespace

---

README.md

Students must be enrolled at ASU

Added requirement for Starbucks internship

---

README.md

update HubSpot link

---

README.md

Update Duolingo link

---

README.md

- Updated links for some internships.
- Closed internships that didn't have any active job postings.
- Improved locations on some of the internships.
Church of Latter Day Saints - I added a LinkedIn link for them because their website's career portal couldn't load.

Internship refactoring

---

README.md

MagView Software Developer Intern position at Fulton, MD.

Added magview intern position

---

README.md

Added canada link for activision

---

README.md

Added CBRE internship

---

README.md

Since they are not accepting for 2022 internships. They told to apply in August for the same.

Removing Citadel

---

README.md

seems like the apple internship was closed for whatever reason. can't find any other summer 2022 positions
closes #354

remove apple internship

---

README.md

Added salesforce swe internship to readme

added salesforce swe internship to readme

---

README.md

add PayPal Intern

---

README.md

Added link to belvedere trading internships

Add Belvedere Trading internships

---

README.md

Just to make it more clear at a quick glance what positions are closed.

Add strikethroughs to closed positions

---

README.md

Finally got it working, still not sure exactly what the problem was. Overwrites and closes #385.

add IMC positions

---

README.md

Solving [issue](https://github.com/pittcsc/Summer2022-Internships/issues/391)

Closed BlackStone Internship 

---

README.md

Closed salesforce

---

README.md

Add Citrix software engineer intern position.

Add Citrix SWE intern position

---

README.md

Added Crestron to the list. Thanks for the work you've been doing!

Add Crestron, edit Mathworks

---

README.md

Add Jina AI

---

README.md

Let me know if any changes are needed! Thank You!
TomTom offers a 12-week Fall, Winter, and Summer program for students enrolled in an undergraduate, graduate, or MBA program as well as a 6-month program for recent grads ready to launch their careers. Perfect opportunity for anyone looking for a Summer 2022 internship and so on.

Add tomtom

---

README.md

There are now multiple positions available for Summer 2022. Quick update to link to those positions.

Update to optiver

---

README.md

Added Jump Trading LLC, Software Engineer Summer Intern position.

Add jump trading

---

README.md

Quora Summer 2022 Software Engineer Remote Internship

added quora summer 2022 internship

---

README.md

Added internship for Wabtec corporation

Add Wabtec internship

---

README.md

7-Month Internship Cycle, January 10 – August 12, 2022 and May 16 – December 16, 2022.

Added Daktronics

---

README.md

Add WeRide.ai position

---

README.md

Added a note regarding eligible majors

Added a note to Vermeer's entry

---

README.md

Added a note regarding visa sponsorship.

Added a note to Workiva's entry

---

README.md

Closed Motional

---

README.md

Add DraftKings

---

README.md

Added a note regarding citizenship requirement

Added note to Johns Hopkins' entry

---

README.md

Closed Quip

---

README.md

Applicants must be eligible for US security clearance;​ all clearances require US citizenship.

update novetta clearance requirement

---

README.md

Note: I added my GitHub at the bototm

Added Dell SWE Opportunity

---

README.md

Added a job posting

---

README.md

Combined both positions into one and added a data science position

Fix duplicate Battelle positions

---

README.md

Added 2 new intern positions (for Epic Games, PNNL)

Added 2 positions

---

README.md

Added Multiple Job ids

---

README.md

Intern at Lemen Technologies is closed

Intern at Lemen Technologies is closed

---

README.md

FaceBook Name Change

---

README.md

👋🏽 Hey guys! Excited to be working together, just added our logo and message. Let me know if there is anything you would like us to change!
CC: @yan-michael

✨ Add Simplify

---

README.md

Whoops, should probs include the exact link for the position...........

Fixing link for Replicon

---

README.md

Added DS and Front End internships :)

Update IBM positions

---

README.md

closed job opening from issue #752 and others.

changing notes of closed positions

---

README.md

[It's not available anymore](https://www.loom.com/i/d8ca82a5fa4b411ab3ee3ac05ca61e01)

Mark Gusto as no longer available

---

README.md

add autodesk, equifax, copart, home depot, mark43 and lucid.

add 6 more roles

---

README.md

Added link for a company

---

README.md

The position is no longer open.

Removed Quora's Data scientist Intern

---

README.md

https://jobs.lever.co/volleythat/33b48dfc-c8ef-4a4f-b48a-8b34795cd0d7

Volley - Software Engineering Intern

---

README.md

- Closed a bunch of positions that are not accepting applications anymore
- Updated positions with newer URLs based on application acceptance.

Updates to existing positions

---

README.md

For more info about our company: https://streamforge.com

Streamforge

---

README.md

Added the Morgan Stanley Technology Summer Analyst position for NYC, NY, as well as my GitHub profile to the list of contributors.

Add Morgan Stanley

---

README.md

Added Akuna Capital job posting, found it through LinkedIn.

Added Akuna Capital Listing

---

README.md

Added Lime

---

README.md

- Added record for Voloridge
- Added self in contributors

Adding Voloridge Investment Management

---

README.md

Updated ReadMe Typo

---

README.md

Add IMC summer intern 2023

---

README.md

LM seems to post positions based on locations, so highly likely more will open up 👍

Added Lockheed Martin

---

README.md

Added Freddie Mac

---

README.md

Adding the Streamforge 2023 Summer Internship

Add Streamforge

---

README.md

Add an opportunity of Code2040

Coder jeffrey patch 1

---

README.md

Added 4 Companies: Valkyrie, Sensata, Peraton & SPS

Added 4 Companies: Valkyrie, Sensata, Peraton & SPS
